use std::env;
use std::path::PathBuf;

fn main() {
    // Only generate headers for the library, not the binary
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let target_dir = env::var("OUT_DIR").unwrap();

    // Configure cbindgen
    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        cpp_compat: true,
        header: Some(String::from(
            "/* AirGapSync FFI Header\n * \n * This header provides C-compatible functions for integrating\n * the AirGapSync Rust library with Swift/Objective-C.\n */"
        )),
        include_guard: Some(String::from("AIRGAPSYNC_H")),
        namespace: None,
        namespaces: None,
        sys_includes: vec![String::from("stdint.h"), String::from("stdbool.h")],
        includes: vec![],
        no_includes: false,
        after_includes: None,
        autogen_warning: Some(String::from(
            "/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */"
        )),
        ..Default::default()
    };

    // Generate the header file
    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(config)
        .with_src("src/rust_core/ffi.rs")
        .with_language(cbindgen::Language::C)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("target/airgapsync.h");

    // Also copy to a more accessible location for Xcode
    let header_path = PathBuf::from(&target_dir)
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("airgapsync.h");

    std::fs::copy("target/airgapsync.h", &header_path)
        .expect("Failed to copy header file");

    println!("cargo:rerun-if-changed=src/rust_core/ffi.rs");
    println!("cargo:rerun-if-changed=src/rust_core/lib.rs");
}
